name: Update Manifest.toml
inputs:
  base:
    description:
      The name of branch to be merged to `target`.
    required: false
    default: 'master'
  target:
    description:
      The name of branch to which `base` is merged.
runs:
  using: "composite"
  steps:
    - name: 'Merge ${{ inputs.base }} to ${{ inputs.target }}'
      shell: bash
      run: |
        base="${{ inputs.base }}"
        target="${{ inputs.target }}"

        git_fetch_origin() {
            git fetch --unshallow origin "$1" || git fetch origin "$1"
        }

        set -ex

        if [ -n "$GITHUB_ACTOR" ]
        then
            git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git config --global user.name "$GITHUB_ACTOR"
        fi

        git_fetch_origin "refs/heads/$base:refs/remotes/origin/$base"
        git checkout -B "$base" "origin/$base"

        git_fetch_origin "refs/heads/$target:refs/remotes/origin/$target" || exit 0
        git checkout -B "$target" "origin/$target"
        git merge --strategy=ours --no-commit "$base"
        find . -type d -name .git -prune -o -type f -print0 | xargs --null rm -rf
        git checkout "$base" -- .
        git ls-tree -r --name-only "origin/$target" | grep -F Manifest.toml \
            | xargs git checkout "origin/$target" --
        git ls-tree -r --name-only "origin/$target" | grep -F Manifest.toml \
            | xargs git add -f --
        git add .
        git commit -m "Merge branch '$base'" || true

        # Since create-pull-request does not like when the current
        # branch is the target branch, checkout master.
        # https://github.com/JuliaFolds/Transducers.jl/pull/167
        if [ "$(git rev-parse --abbrev-ref HEAD)" != "$base" ]
        then
            git checkout "$base"
            git merge --ff-only "$target"
        fi

        git ls-tree -r --name-only "origin/$base" | grep -F Manifest.toml \
            | xargs git checkout "origin/$base" --
        git ls-tree -r --name-only "origin/$base" | grep -F Manifest.toml \
            | xargs git add -f --
